.TH XV 1 "22 April 2007" "Rev. 3.10a-jumboFix+Enh"
.SH NAME
\fBxv\fP \- interactive image display for the X Window System
.SH SYNTAX
.B xv
.RI [ options ]
.RI [ filename [ filename... ]]
.SH DESCRIPTION
The
.I xv
program displays images on workstations and terminals running the X Window
System, Version 11.  Supported image formats include
PBM, PGM, PPM, X11 bitmap, XWD, XPM, Utah Raster Toolkit RLE, PDS/VICAR,
FITS, Sun Rasterfile, GIF, PCX, Targa/TGA, BMP, WBMP, IRIS RGB, Spectrum
SCREEN$, PM, and optionally PNG, JPEG, JPEG 2000, JP2, TIFF, PostScript,
PDF, G3 fax, MAG, PIC, MAKI (640x400), PI, and PIC2.
.LP
Aside from the usage screen (available by typing 'xv -help' at the command
line), documentation for XV is now distributed
.I only
as a PostScript (or PDF) file, as it has gotten enormous
and is no longer very well suited to the 'man' page format.
Print a copy of the (100-ish page) manual found in
.IR docs/xvdocs.ps .
If you are unable to get the manual to print on your printer,
you may purchase a printed copy of the XV manual.  Click on 'About XV' in
the program to get further information.
.PP
If you don't 
.I have
the PostScript file, it is part of the standard XV distribution, the
latest version of which can be obtained from
.IR http://www.trilon.com/xv/
or via anonymous ftp from 
.IR ftp.cis.upenn.edu
in the directory pub/xv .
.PP
This version has been patched with the XV Jumbo Patches, available from
.IR http://pobox.com/~newt/greg_xv.html .
.PP
.SH AUTHOR
John Bradley (and many contributors)
