.\" $Id: $
.\" Translated into finish by root (root@rk2)
.\"
.TH XV 0 "7. Huhtikuuta 1998" "Rev. 3.10" "K‰ytt‰j‰n sovellusohjelmat"
.SH NIMI
\fBxv\fP \- interaktiivinen kuvan n‰ytt‰j‰ X Window System:ille
.SH SYNTAX
.B xv
.RI [ optiont ]
.RI [ tiedosto [ tiedosto... ]]
.SH KUVAUS
.I xv
n‰ytt‰‰ kuvia jotka ovat GIF, JPEG, TIFF, PBM, PGM, PPM, X11 bitmap, Utah Raster
Toolkit RLE, PDS/VICAR, Sun Rasterfile, BMP, PCX, IRIS RGB, XPM, Targa, XWD, 
mahdollisesti PostScript, ja PM formaatissa, tyˆasemilla ja terminaaleille, 
joilla ajetaan X Window System version 11:ta. 
.LP
XV:n dokumentaatiota levitet‰‰n nyt
.I vain 
PostScript tiedostona, koska siit‰ on tullut suunnaton ja se ei ole 
en‰‰ solveltuva 'man' -sivu muotoon. 
Tulosta kopio (100 sivuisesta) ohjekirjasta
.IR docs/xvdocs.ps .
Jos et pysty tulostamaan ohjekirjaa tulostimellasi, sinun t‰ytyy ostaa painettu 
kopio XV ohjekirjasta. Valitse 'About XV' ohjelmassa saadaksesi lis‰tietoja.
.PP
Jos sinulle ei ole PostScript tiedostoa, joka on osa standardia XV levityst‰,
uusin versio on saatavilla anonyymi ftp palvelimelta, 
.IR ftp.cis.upenn.edu
hakemistosta /pub/xv.
.PP
.SH AUTHOR
John Bradley
.SH "KATSO MY÷S"
