#!/bin/csh -f
#
# simple script to change all 'static char' references in bitmap files to
# 'static unsigned char' (to appease those compilers that don't like 
# values > 0x7f assigned to a signed char)
#
# --jhb, 3/21/94

foreach i (bits/*)
  if ( ! { grep -q unsigned $i } ) then
    echo $i
    sed -e 's/static char/static unsigned char/' <$i >$i.foo
    mv $i.foo $i
  endif
end
