.\" {PTM/LK/0.1/28-09-1998/"xvpictoppm - konwersja miniatury XV do .ppm"}
.\" T³umaczenie: 28-09-1998 £ukasz Kowalczyk (lukow@tempac.okwf.fuw.edu.pl)
.TH xvpictoppm 1X
.SH NAZWA
xvpictoppm \- utwórz przeno¶n± pixmapê (.ppm) z miniatury (thumbnail) XV
.SH SK£ADNIA
\fBxvpictoppm\fP
.SH OPIS
\fBxvpictoppm\fP odczytuje miniaturê (thumbnail) utworzon± przez XV
(znajduj±c± siê w podkatalogach '.xvpics') ze standardowego wej¶cia.
Nastêpnie zapisuje na standardowe wyj¶cie przeno¶n± pixmapê (.ppm). Mo¿e to
byæ u¿yteczne przy umieszczaniu miniatur na stronach WWW lub przy podobnych
zastosowaniach.
.PP
.SH AUTOR
John Bradley  -  bradley@dccs.upenn.edu

