.\" {PTM/LK/0.1/28-09-1998/"xvpictoppm - konwersja miniatury XV do .ppm"}
.\" Tłumaczenie: 28-09-1998 Łukasz Kowalczyk (lukow@tempac.okwf.fuw.edu.pl)
.TH xvpictoppm 1X
.SH NAZWA
xvpictoppm \- utwórz przenośną pixmapę (.ppm) z miniatury (thumbnail) XV
.SH SKŁADNIA
\fBxvpictoppm\fP
.SH OPIS
\fBxvpictoppm\fP odczytuje miniaturę (thumbnail) utworzoną przez XV
(znajdującą się w podkatalogach '.xvpics') ze standardowego wejścia.
Następnie zapisuje na standardowe wyjście przenośną pixmapę (.ppm). Może to
być użyteczne przy umieszczaniu miniatur na stronach WWW lub przy podobnych
zastosowaniach.
.PP
.SH AUTOR
John Bradley  -  bradley@dccs.upenn.edu

